name: Run Cache Warmer Every Days 2 Times

on:
  schedule:
    - cron: "0 0 * * *"  
    - cron: "0 12 * * *"   
  workflow_dispatch:

jobs:
  warm-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run Cache Warmer
        run: npm run start
        env:
          BRD_PROXY_ID: ${{ secrets.BRD_PROXY_ID }}
          BRD_PROXY_AU: ${{ secrets.BRD_PROXY_AU }}
          BRD_PROXY_AE: ${{ secrets.BRD_PROXY_AE }}
          BRD_PROXY_SG: ${{ secrets.BRD_PROXY_SG }}
          BRD_PROXY_UK: ${{ secrets.BRD_PROXY_UK }}
          BRD_PROXY_BR: ${{ secrets.BRD_PROXY_BR }}
          BRD_PROXY_FL: ${{ secrets.BRD_PROXY_FL }}
          BRD_PROXY_IN: ${{ secrets.BRD_PROXY_IN }}
          BRD_PROXY_DE: ${{ secrets.BRD_PROXY_DE }}
          BRD_PROXY_NL: ${{ secrets.BRD_PROXY_NL }}
          BRD_PROXY_DK: ${{ secrets.BRD_PROXY_DK }}
          BRD_PROXY_ES: ${{ secrets.BRD_PROXY_ES }}
          BRD_PROXY_US: ${{ secrets.BRD_PROXY_US }}
          BRD_PROXY_FR: ${{ secrets.BRD_PROXY_FR }}
          BRD_PROXY_CA: ${{ secrets.BRD_PROXY_CA }}
          BRD_PROXY_MX: ${{ secrets.BRD_PROXY_MX }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          APPS_SCRIPT_URL: ${{ secrets.APPS_SCRIPT_URL }}
